### ISSUE TITLE
Play - Suheyla's suggestion

### ISSUE THREAD

**Issue by clintmclean** [robertocarroll/barjeel-app#10]
I'm not sure what I think of this - our question style is maybe a bit 'smarter' but maybe the easy way is equally entertaining? Suheyla will be fine if we feel we need to stay with the original... but let's just think about if we do.

From Suheyla:

To be frank, it's quite hard coming up with questions. I'm not saying we should abandon the idea or anything like that. I'm just saying that it may take a while. Or perhaps we can shift our strategy a little.

Imran showed me this iTunes app that he has on his ipod, where the app pulls out songs from an existing database, and pulls out 3 singers' names, and asks you to identify which singer sings the song (see his email in blue below). Perhaps we can make the game something simple like that? Like identifying artists in relation to artworks? This way we can allow for a whooole lot more questions, basically as many questions as there are artworks. What do you think?

Here’s the quiz app I told you about http://bgr.com/2014/05/23/music-quiz-iphone-app-download/

It’s based on the quiz game that’s on iPods. It takes music in your library and asks you to identify the song. Countdown timer gives you your score.

You can check out the app here on iTunes App Store

https://itunes.apple.com/us/app/music-quiz-do-you-know-your/id878463689?mt=8

**Comment by UnaJanicijevic** [comment]
I think the connection game has a more meaningful underlying thread about themes/places/things that unite artists and artwork. The straight up — who did it — game is not so meaningful to me.
But maybe I'm not the target audience.

**Comment by robertocarroll** [comment]
Closing this issue for now. We seem to have content coming in for the connections approach.
