### ISSUE TITLE
Approach to image optimisation, esp for retina screens

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#11]
Not sure exactly the best way to do this but need to investigate, e.g. http://www.filamentgroup.com/lab/compressive-images.html
These include: 
- Loading screen logo
- Question images
- Connect images (curator, content images)

**Comment by clintmclean** [comment]
Lots here to digest. One thing to keep in mind is using a reasonably good standard image doesn't ruin the experience for a retina user - it is mildly diminished but if the images are not mixed (retina and non-retina) on the same site it is less obvious. Let me do a couple tests and then maybe we can test a few online to find our sweet-spot. This would be easier is we weren't dealing with images of artwork that need to be pretty faithful.

**Comment by clintmclean** [comment]
Here is a link to 3 images each sized 5 different ways.
I did one at 150% of retina size - I don't think it is worth trying 200%. Oversizing and then over-compressing has a lot of associated problems and I would lean heavily towards a retina sized at 100% and compressed medium-low. There is a lot of discussion about all this and no great consensus but it seems to me people are generally (maybe you know better) using the @2x to serve a file for retinal and a different file for the others. In this case I'd lean towards 768px images at 50-60 compression.

I've colour-coded the matching sizes in this link and named with px size and compression:
https://www.dropbox.com/sh/vrwab6axzo6id69/AADjx47y1qvbEjO7FIW_T2QDa?dl=0

**Comment by clintmclean** [comment]
Also keep in  mind most of our images won't need to be full screen necessarily so these kb sizes would be less.

**Comment by robertocarroll** [comment]
Excellent. Thanks for the experiments. You're right about the @x2. I'm going to use something like this:
http://imulus.github.io/retinajs/

The only thing to be aware of is the naming convention: for example my_image.png and my_image@2x.png, so basically you add @2x to the end of the filename and it should all work well! 

Closing this issue.

**Comment by robertocarroll** [comment]
Adding this link about ideal image size as it might come in useful: 
http://www.themepunch.com/faq/ideal-image-size/
