### ISSUE TITLE
Fonts - do we have fonts in .tff format / license?

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#12]
What are the fonts? How are we going to serve them fonts? What are the rights for using them within an app? Currently served through Typekit which will not work in an app context? Do we have them locally?

**Comment by clintmclean** [comment]
How are fonts typically served? I think Una needs to let us know what we have licenses for - we discussed on the phone but I cant' recall specifics. I think we have some but not all...
Fonts are OTF

**Comment by robertocarroll** [comment]
Barjeel webfonts are served out of Typekit. We can't use Typekit for a native web app. We need .tff files which will be hosted locally, i.e. in the app.

**Comment by clintmclean** [comment]
Here is a link to ttf fonts.
Not sure if Belinda is the final choice for script so for now we could leave as Gotham until Una is back to weigh in.
https://www.dropbox.com/sh/bn487lmlaoao3xe/AABXhrRgiMJl0T28k2RtlH2Ua?dl=0

**Comment by UnaJanicijevic** [comment]
i have a license for both Belinda and Gotham
