### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#13]
What are the font sizes in the design? 

Specifications for the relative font sizes (ems or rems) for each part of the design.

**Comment by clintmclean** [comment]
I'm going to work this out and get back to you.

**Comment by clintmclean** [comment]
If I have done this correctly - our body copy must be tied to a pt size which becomes 1em. I've made our smallest type this value (a supposed 16pt - if we adjust this all the others adjust accordingly).
Here is a link to a pdf marking sizes on the app. 
https://www.dropbox.com/s/5xz310vuwkcubca/app-fonts-em1.pdf?dl=0

H1 - 2.65 em 
H2 - 1.6 em
H3 - 1.3 em
H4 - 1 em (assumed at 16pt)

**Comment by robertocarroll** [comment]
Thanks! (I could have done this but not from the pdf. Hope it wasn't too much work. Much appreciated.)

Closing this issue.

**Comment by robertocarroll** [comment]
Forgot to ask for the associated line-heights. Thanks!

**Comment by clintmclean** [comment]
I hope I did this correctly - I am still basing each em off that initial 16 and not off each H1, h2, h3 size.
That 16 is purely a guess so we may need to finesse that a bit but I think using this system we just need to finesse that one and the others will fall into place - right?
H1 - 2.65 em - line height3.49 em 
H2 - 1.6 em - line height 1.49 em 
H3 - 1.3 em - Line height 1.8 em
H4 - 1 em (assumed at 16pt) - line height 1.2127
Are you using these H classes? If so, we can use them to refer to sizes to make things a bit easier if you are looking for size on a specific piece of text.

Text that does not have two lines does not have line height so its position on the page I guess needs to be estimated and then finessed? Or...? I can't set a ruler to M sizes...

**Comment by robertocarroll** [comment]
Thanks. I'm using REMs so it's all based off the size set in the initial html declaration which is currently 16px. 

Using h1, h2, h3 etc as well as a helper class so the sizes can be used elsewhere as well, i.e. not in headings. You can use these to refer to the size if you like. 

h1, .alpha 
h2, .beta 
h3, .gamma
h4, .delta
