### ISSUE TITLE
HTML5 encoded videos

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#15]
Sample video in HTML5 formats. Need to investigate the formats required for Safari / Chrome, i.e. http://blog.zencoder.com/2010/09/30/how-to-encode-video-for-mobile-use/

**Comment by clintmclean** [comment]
Hi have put three sizes of video with an h264 codec (very universal) in the dropbox data folder. These are only test files.

**Comment by robertocarroll** [comment]
Thanks. Closing this issue.
