### ISSUE TITLE
Add other testing devices

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#18]
- Regenerate the Apple provisioning profiles
- Document how to do this process a bit better

**Comment by clintmclean** [comment]
Hi - it worked! I now have it on my phone. I think it is to early for feedback on how it works right? …I mean it does work, just not as we want it to as a final product. Right?

**Comment by robertocarroll** [comment]
If you can open issues or add to existing issues with feedback that would be great.
