### ISSUE TITLE
Quiz structure

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#2]
The quiz in the designs (AppDesigns1.pdf) is structured: 
## 1. Show connection

![appdesigns1 6-6](https://cloud.githubusercontent.com/assets/1565953/5710240/56c1617c-9a98-11e4-9929-553f4f4ee14e.jpeg)
## 2. Show possible answers

(These are going to need some kind of radio buttons to allow the user to select.)
![appdesigns1 7-7](https://cloud.githubusercontent.com/assets/1565953/5710243/5cc9052a-9a98-11e4-9bd7-bf2b118f370d.jpeg)
## 3. Incorrect - try again - Lose a life

![appdesigns1 8-8](https://cloud.githubusercontent.com/assets/1565953/5710247/638e4730-9a98-11e4-8c92-aeb8152278db.jpeg)
## 4. Correct - Click to next question

![appdesigns1 9-9](https://cloud.githubusercontent.com/assets/1565953/5710249/6a3cc732-9a98-11e4-9eff-3053855e0521.jpeg)
## Questions
1. The current dev prototype has a different structure: ask a set number of questions from a larger question bank, user selects and submits, correct / incorrect, next question, show user-score out of total at the end, e.g. 6/10. Do you think the lives structure above is more compelling? 
2. If so, do the questions keep coming until the user loses all lives? 
3. Lives are the only metric - because the user can guess again. Is this enough to keep someone coming back? i.e. there's no memorable metric, e.g. last time I got 6/10, only a "feeling" of doing better / worse than last time.

**Comment by UnaJanicijevic** [comment]
I personally prefer lives to a score (6/10.. feels like school). And since there is no network, there is nobody to compete with anyway.
Maybe another thing to consider instead of lives is rewarding a winning streak, say getting 3 question right in a row gives you a star and you collect stars ...or... 3 wins in a row replenish your lost lives maybe if we stick with the lives structure.

**Comment by robertocarroll** [comment]
OK. Let's stick to that structure. Closing this issue.

**Comment by robertocarroll** [comment]
From Clint:
For the score vs hearts discussion - I like hearts or lives or whatever too though after you 'die' and use all your hearts maybe it could say something like Game Over you got 7 out of 10 correct. It then gives kids something to beat so there is a measure of them improving or being better than their peers which makes it more fun I think.
