### ISSUE TITLE
How best to manage content / image updates? 

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#20]
Need to look into this. Neither prose nor dropbox seem to be working very well.

**Comment by robertocarroll** [comment]
I've had a bit of clean up and here's the current situation:
- The main branch of this repository contains the dev files for the app.
- Content needs to go in the 'data' folder: https://github.com/robertocarroll/barjeel-app/tree/master/app/data 
- I then have to build the app, which creates a version in the dist folder and also updates the gh-pages branch. This allows us to preview the app at http://robertocarroll.com/barjeel-app
- Phonegap build is set to build from the gh-pages branch of this repo. 

Please take a look at the readme file for some of the details around the required images, as well as the latest versions of the content in https://github.com/robertocarroll/barjeel-app/tree/master/app/data 

There's quite a few changes to the json and the images which perhaps we can chat about in Slack. 

In terms of the best way to update the content, I think it's best that you don't work in Github. Perhaps you can delete that fork so we don't get confused. Instead if you put your stuff in the data folder of the shared Dropbox folder for barjeel-app-public and tell me and I can copy it over. It's the only way I can think that we can keep track on top of updates without Github.

**Comment by clintmclean** [comment]
Hi - I am back!
There are a lot of questions/comments I'll work through.
It looks like you maybe deleted the fork already? I"m not seeing it - or
maybe I am not looking in the right place...

**Comment by robertocarroll** [comment]
Your fork is still there: https://github.com/clintmclean/barjeel-app-public 

But I think it best to work locally and then send the updates to me. It's the only way I can see to keep on top of everything and to have a stable process to build the app.

**Comment by robertocarroll** [comment]
Closing this issue as we've discussed it and CM is going to update the data folder in dropbox and I will rebuild the app.
