### ISSUE TITLE
How to randomise questions and keep track of done questions

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#22]
- Shuffling a Backbone collection
- Keeping the used questions in localstorage
- Resetting them when the stock gets low.
## References
- http://stackoverflow.com/questions/12989994/calling-shuffle-on-a-filtered-backbone-collection
- http://stackoverflow.com/questions/16353865/backbone-js-grabbing-the-length-of-a-collection-for-use-with-random-number
- http://stackoverflow.com/questions/16754948/backbone-js-how-to-shuffle-items-within-a-collection
- http://www.mattzeunert.com/2013/01/26/minimal-backbone-localstorage-example.html

**Comment by robertocarroll** [comment]
We need to consider the UX for serving questions. Will it be random from the question bank? Does it matter if the user sees the same question twice? If not, we will have to store the questions the user has done and keep track on them. Then what happens when they go through the question bank and get to 1 question left? Reset the question bank?

**Comment by clintmclean** [comment]
Yes I think the questions need to random - otherwise replaying the game isn't very interesting.
When they get through all the questions (I spoke to Suheyla and the new target for launch is 100 questions). what if it just said - Congratulations you have answered XX out of 100 questions correctly! (it would have to be 98 or 99 out of 100 as they die after 3 incorrect answers).

**Comment by robertocarroll** [comment]
I was thinking more about the usage case for repeated plays. So we would keep track of the done questions and a user would play the game 10 times and answer 10 questions each time ... do we expose the fact that they have done all the questions or not?

**Comment by clintmclean** [comment]
A 10 question game would be really quick though - why not let them play until they lose three lives or 100 questions - whichever comes first?

**Comment by robertocarroll** [comment]
That's not what I'm saying. 

The user will continue playing until they lose all three lives and they might make it to 100 questions if they are amazing. Those two use cases are clear. 

I'm talking about the details of how the random questions work: 
- Does it carry over sessions? So when a user starts playing again he or she will definitely not see a question he has seen before. 
- What happens when they reach 100 without really realising they have reach the end of the question bank? Do we draw attention to it or not?

**Comment by clintmclean** [comment]
ah I see.
I would say between sessions the questions can repeat and I would make a hard stop at 100 questions saying they've made it to the end -I think they'll remember questions when they repeat so better to just say You Did It! or something. Agree or disagree?

**Comment by robertocarroll** [comment]
I'm not sure. I think it probably should keep track of done questions - as you say they will probably remember ones they've done, even between sessions. Did I misunderstand you there? 

When they reach 100 - either in a single session or across many sessions - it can say well done! but shouldn't they then have the option to play again?

**Comment by clintmclean** [comment]
Ok I think your suggestion is better - if we can do that it sounds good to me.
Yes I think play again option is good too. How about Congratulations! You scored XX/100.
Would You Like to Play Again?

**Comment by robertocarroll** [comment]
Done using HTML5 localstorage to keep track of done questions and serve random one from remaining questions. When all questions are done goes to congratulations template. Tap on play again to reload the questions from questions.json and begin the whole thing again.

**Comment by robertocarroll** [comment]
Re-opening this issue: 
- [x] Need to check if browser supports localStorage and manage what to do if it does or doesn't: http://diveintohtml5.info/storage.html
- [ ] Need to alter behaviour if you run out of questions. Make it so that you can't start the play section on zero questions and get taken to the game over screen.

**Comment by robertocarroll** [comment]
We've decided to scrap this approach and just pull from the same question bank on each new play. Closing this issue.
