### ISSUE TITLE
Modal window to view larger play images 

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#23]
User can tap on an image in the answer to see it bigger. Opens in a modal window.

**Comment by robertocarroll** [comment]
Do we definitely want this feature? I realise the reasoning behind this feature, but I'm just checking because it adds to the image requirements considerably. Without it, each question would just need the square images, but this adds the need for the full image as well.

**Comment by clintmclean** [comment]
Hi - yeah it is too bad we can't do both in one but it definitely important to show the full image somewhere and I can't think how we could do it instead of thumbnails or something.

**Comment by robertocarroll** [comment]
There's is a technical constraint here. Each question will have an extra 400-500kb with the full images. If we have lots of questions that will make the app very heavy to download on install. 

Perhaps this is the point at which the app crosses over into the website? The round image could open a link to the full image on the Barjeel site using the in-app browser.

**Comment by clintmclean** [comment]
Hi - the @2x image sizes are more between 125-250kb (each).
I don't see how we can have an app based on artworks and not show the
artworks. I think it is essential for the game to be useful.
Our images are not large compared to what a lot of apps do with images for
ipads etc - I don't know anything about the tech of how they do it, but
having links seems like a bad idea to me. Maybe the difference is with a
lot of image heavy apps people are expecting them to be heavy but wouldn't
be for a game-based app like ours. And I guess it needs to download all in
order to be used off-line… I don't know what the answer is here - wanna
discuss on skype tomorrow?

C.

**Comment by robertocarroll** [comment]
Why do the links seem like a bad idea? Could you elaborate? I think it's a very good idea which balances the requirement to view the full image with all the other issues. The experience of viewing the image would arguably be better than provided in the app because all the relevant metadata etc will be there and the image will be in the context of the collection. Sorry, but I can't do tomorrow. How about Wednesday?

**Comment by clintmclean** [comment]
Is it possible to do a test with this without too much pain on your part? I
just think leaving the app after each question isn't very nice for the flow
of the game and it means we are not functional if off-line which was part
of the thinking in having the app download wasn't it? ..should we rethink
that? What if the app wasn't available when off-line? Does that solve the
image size issue?
Ok lets try wed - I have a suit fitting and an interview and friends coming
for a goodbye dinner but will try to carve out an block to catch up - I
think we need it!

C.

**Comment by clintmclean** [comment]
Was looking at how other apps do this again - sometimes it opens just the larger image onto black and it is quite instantaneous - and sometimes it loads a page with a url. Which of those two (or was it a third way) were you suggesting? I am wondering also if we can reduce the px dimensions of our images to help reduce file size.but the chrome link where wanted to see the dimensions on various apps isn't loading anymore - did you change the url?

**Comment by robertocarroll** [comment]
Url is the one for this repo. It's robertocarroll.com/barjeel-app

**Comment by robertocarroll** [comment]
Url is the one for this repo. It's robertocarroll.com/barjeel-app

**Comment by robertocarroll** [comment]
I suugested getting the image and the data from the website but loading it as  json so it can be styled in the app and opened in the in-app browser - not just like opening the whole website in Safari etc

**Comment by clintmclean** [comment]
oops. I had the public-app url. All good.
I emailed Una directly with that url but copied the message into github for archiving (in case you are thinking she won't see it there).

I think opening the browser window is going to be cumbersome to repeatedly be doing but maybe a test is the best way to know for sure - can you demo that? I'll look into reducing file sizes by reducing px dimensions which would mean the full image pics aren't big and glorious but would be more feasible.

**Comment by robertocarroll** [comment]
I've added a quick test for the larger images just to see what the reaction is: 
1. Go to a question and get it right. 
2. Tap on either test modal 1 button or test modal 2 button
3. It should open a modal with the image being pulled from barjeelfoundation.org

It's all hardcoded at the moment so it only shows the same image for every question.

**Comment by robertocarroll** [comment]
> The pop up for the larger images on the play section look good to me - pretty seamless.

So we need the url of the each image from the website and any other information we want to display there, e.g. title, artist. 

Closing this issue.
