### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#34]
Reported case of slow loading of play questions.

**Comment by robertocarroll** [comment]
Which device are you using?

**Comment by robertocarroll** [comment]
It's odd: I have what I would consider to be our lowest supported device - iPhone 4 running iOS7 - and it all works smooth and quick.

What exactly happens? You swipe left from the play intro screen and ...

**Comment by clintmclean** [comment]
Oh I assumed I may have had the oldest phone. Yeah so when the intro screen comes up it takes maybe 20 seconds before I can swipe to advance - and even knowing it takes a long time I am still constantly swiping to see if it is ready yet.

**Comment by clintmclean** [comment]
ok I just counted and it is 10 seconds before I can proceed.

**Comment by clintmclean** [comment]
If I click the back-arrow and try to proceed again, it takes the same amount of time again though - shouldn't it be immediate once it loads once?

**Comment by robertocarroll** [comment]
So what is your device and iOS?

**Comment by clintmclean** [comment]
8.4.1  - let me try updating now.

**Comment by robertocarroll** [comment]
Oh - no I'm on iOS7 so that shouldn't be the issue.

**Comment by robertocarroll** [comment]
OK. So long discussion this could be related to the swipe rather than the loading of the app.

**Comment by robertocarroll** [comment]
Removing splash screen hopefully solves this issue. Closing.
