### ISSUE TITLE
Close icon svg not showing up

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#36]
The close icon provided doesn't show up on my iPhone 4. I spent a long time debugging and tried various ways to make it show, eg background image, img tag, etc. but nothing worked. 

CM provided a new version but this didn't work either. Currently a placeholder SVG is in there. Please can you review the SVG and provide one in the same format as all the others (which all work) and I will put it in. Thanks!

**Comment by clintmclean** [comment]
OK - I asked Una last night to make one as an ai file as she did the others and then I will take that and make it an svg as I did the others. I don’t know what has changed in this version other than I created it in a different illustrator version than the others so we’ll make the new one with the exact process of the other ones.

**Comment by robertocarroll** [comment]
New close icon shows on iPhone 4. Closing this issue.
