### ISSUE TITLE
Home - What's the user interaction to get from 1.2 to 1.3?

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#4]
Using the latest designs (AppDesignsUpdate1.pdf), it's not clear how the user gets from page 1 to page 2, e.g. Tapping on "play" area in page 1, I would expect to go straight to the "play" section. 

![barjeel-app-user-journeys 1-1](https://cloud.githubusercontent.com/assets/1565953/5778255/d6d23e3a-9d91-11e4-92a3-046e0e514474.jpeg)

**Comment by clintmclean** [comment]
1. agree - tap tap tap

**Comment by robertocarroll** [comment]
So 1.3 should be this screen from a tap in 1.2. Where does the other view with three regions and the longer text come in?  
![appdesignsupdate1 5-5](https://cloud.githubusercontent.com/assets/1565953/5839203/8931b128-a184-11e4-966e-5626aad9804a.jpeg)

**Comment by UnaJanicijevic** [comment]
I don't think we need the one with 3 icons & descriptions at all.
It would be 3 icons and names _click_ sections with description

**Comment by robertocarroll** [comment]
This makes sense. I've made it so that we go from 1.2 to the big splash view. 

Closing this issue.
