### ISSUE TITLE
Connect - Questions about user flow

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#7]
I have a few questions here: 
1. Do you think the title and action should change on 3.2, so that it returns the user to the connect list rather than the app home? 
2. What’s the user interaction to get between screen 3.2 and screen 3.3?
3. What’s the user interaction to get between screen 3.3 and screen 3.4?
4. What happens at the end of the sequence? i.e. when there are no more images? 

![barjeel-app-user-journeys 3-3](https://cloud.githubusercontent.com/assets/1565953/5778359/ac531462-9d92-11e4-89bf-b3c65dd214af.jpeg)

**Comment by clintmclean** [comment]
1. yeah I agree - I actually wonder if we need those to return home at all or if we just have a home icon in the bottom bar so we can free up that top bar for such actions (without then losing consistancy of it always being section home 'except when'…)
2. I like swipes when there is only one element and taps when there are many. For example on the Home page we have three elements - I would tap (as you suggested) to go inside one of them and then swipe once in it.
3. Swipe as above. I am not sure we need Next buttons actually on 3.4 I think swiping is becoming intuitive and lots of apps seem to let users just work it out.
4. Good question! Maybe swipe brings you back to 3.1 or it guides us somehow to an upward swipe which returns to 3.1? Should we number 1 to 5?
5. NEW COMMENT - I don't think we can have the little portrait overlapping the artwork in the design on 3.4

**Comment by UnaJanicijevic** [comment]
lets discuss specifics over skype? we might need to talk this out to figure out what's best.

**Comment by robertocarroll** [comment]
I've actually implemented it without the three tabs at the bottom and only the title bar at the top, which I think works quite well, but hope to show you it all by the end of the week. 

Re: Clint's point 5 above, I've removed the curator image from 3.4 for now.

**Comment by robertocarroll** [comment]
Closing this issue. Working in production.
