### ISSUE TITLE
Home - animations: Can the eye blink a few times? Cards shuffle? Etc.

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#8]
Yes. It is possible to animated icons using the svg format: http://css-tricks.com/guide-svg-animations-smil/

I think you can export svg animations from Illustrator.

**Comment by robertocarroll** [comment]
We need to be very sensitive to performance with animations especially on older devices. Need to experiment. 

Also icon fonts is the best way to go for icons. Do you gave any experience with making a custom icon font?

**Comment by UnaJanicijevic** [comment]
On animation: I couldn't figure out how to use the svg animation program, but I have the various 'key frames' built in illustrator. If we decide we can support animation we can talk about next steps.

No experience with icon fonts. I know it's doable in fontographer, but never tried. The program is really pricey but I can look into stealing it somewhere...?

**Comment by clintmclean** [comment]
I'm not sure if it is the same but I can do animated gifs - I can try and make svg animation and see if I can figure it out. Ditto on icon fonts. There is an open source one I was looking at - maybe  it isn't the same...

**Comment by UnaJanicijevic** [comment]
yea, I made some animate gifs of the frames I had, but they're not perfect since they don't do any frame blending in between, so it's really choppy.
plus I'm not sure Rob can use gifs in the app...?

**Comment by robertocarroll** [comment]
We need to try one of the svg animations and a static one before you do them all so we can check the quality and how they look.

**Comment by robertocarroll** [comment]
Take a look at this for the thinking behind .svg instead of icon font: http://gomakethings.com/using-svgs/

If you could make a single sprite that would be great, but I'm not sure it's important since we're not loading over the web. Also I don't think we need to worry about fallbacks because our target devices support svg

**Comment by clintmclean** [comment]
I've added an svg called Play3.svg into the images folder of the barjeel
public dropbox folder. Want to try it out and make sure it is ok and then I
can add the others?

**Comment by robertocarroll** [comment]
Thanks. This icon is live now: http://robertocarroll.com/barjeel-app/

It will work well I think, but in the original file you provided the artboard / canvas wasn't big enough for the entire image so some of it got cropped. 

Also do we want to try an animation? 
These two articles explain the process: 
- http://codyhouse.co/gem/animate-svg-icons-with-css-and-snap/
- https://css-tricks.com/guide-svg-animations-smil/

**Comment by robertocarroll** [comment]
We didn't mention this last night, so closing. Please re-open if you're still keen on the idea.
