### ISSUE TITLE
Connect icons

### ISSUE THREAD

**Issue by UnaJanicijevic** [robertocarroll/barjeel-app#9]
Not sure if I shared the alts. Here they are:
![screen shot 2015-01-24 at 2 29 03 pm](https://cloud.githubusercontent.com/assets/4991415/5888662/859c20da-a3d6-11e4-93b4-50721a1e1704.png)

**Comment by clintmclean** [comment]
I don't know - maybe the people feel the most personal. I keep seeing a clock sort of. Handshake feels like a bank to me.

**Comment by UnaJanicijevic** [comment]
yep, handshake is business & link is generic.
if we went down from 3 people to just two would it be better, or seem like a dating thing?

**Comment by clintmclean** [comment]
Two may seem like it is more of a Contact (between them and us) rather than connect? What if the three had little arms connecting them like ring-around-the-rosey?
I don't think it is anything that is going to hurt the game terribly so if we don't find an alternate it isn't the end of the world.

**Comment by UnaJanicijevic** [comment]
cute idea, sadly looks super weird. esp. at a small size
![screen shot 2015-01-24 at 3 05 16 pm](https://cloud.githubusercontent.com/assets/4991415/5888772/79ee6582-a3da-11e4-8872-f5beeaced904.png)

**Comment by UnaJanicijevic** [comment]
I think it needs to be obvious, rather than clever when it's so small

**Comment by robertocarroll** [comment]
I'm going to close this issue as it's incorporated in #24 

Feel free to re-open if there's more to discuss.
